//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IW.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.userId = new Guid("00000000-aaaa-bbbb-cccc-ddddeeeeffff");
        }
    
        public int id { get; set; }
        public System.Guid userId { get; set; }
        public string userName { get; set; }
        public short Sex { get; set; }
        public short Age { get; set; }
    }
}
